apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector-db
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-app-user
  namespace: vector-db
type: Opaque
stringData:
  username: appuser
  password: test@123

