apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgvector
  namespace: vector-db
spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  bootstrap:
    initdb:
      database: vectordb
      owner: appuser
      secret:
        name: pg-app-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;

  storage:
    size: 20Gi

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
